#!/bin/sh
# Copyright (C) 2008-2010  Equinox Software, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Slony replication status nagios check
# Written by: Equinox Software, April 19, 2010 - Lee Dickens
. /etc/profile
count=`PGUSER=postgres psql -U evergreen evergreen -c "select st_lag_num_events from _replication.sl_status;"|sed -n 3p|sed 's/^[ \t]*//'`
if [ $count -gt 200 ]; then
   echo "CRITICAL: Slony Replication Lag: st_lag_num_events = $count"
   exit 2
fi
if [ $count -gt 150 ]; then 
   echo "WARNING: Slony Replication Lag: st_lag_num_events = $count"
   exit 1
fi
echo "OK: Slony Replication In Sync: st_lag_num_events = $count"
exit 0

